steps:
  - name: gcr.io/kaniko-project/executor
    args:
      - --destination=gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME
      - --destination=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=12h

timeout: 720s
options:
  machineType: 'N1_HIGHCPU_8'